pipeline {
      agent any
      stages {
        stage('Build Application') {
          steps {
            sh 'mvn -f java-tomcat-sample/pom.xml clean package'
          }
          post {
            success {
              echo "Now Archiving the artifacts..."
              archiveArtifacts artifacts: "**/*.war"
            }
          }
        }
          stage('Deploy Stage Env') {
            steps {
              build job: 'Deploy_Application_Staging_Env_Pipeline'
            }
          }
          stage('Deploy Prod Env') {
            steps {
              timeout(time:5, unit:'DAYS'){
                input message:'Approve PRODUCTION Deployment?'
              }
              build job: 'Deploy_Application_Prod_Env_Pipeline'
            }
          }
      }
}
