pipeline {
  agent any
  stages {
    stage('Init') {
      steps {
        echo 'Package_Application - Init'
      }
    }
    stage('Build') {
      steps {
        echo 'Package_Application - Build'
      }
    }
    stage('Deploy') {
      steps {
        echo 'Package_Application - Deploy'
      }
    }
  }
}
